steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.api', '-t', 'us-central1-docker.pkg.dev/smartcart-ai-dev-499914/cloud-run-source-deploy/smartcart-buildweek-api', '.']
images:
  - 'us-central1-docker.pkg.dev/smartcart-ai-dev-499914/cloud-run-source-deploy/smartcart-buildweek-api'